### ISSUE TITLE
Spacefish prompt derps on ^C for prematurely aborted commands

### ISSUE THREAD

**Issue by Snuggle** [matchai/spacefish#50] opened 2018-07-25 00:08 UTC
## Bug Report

**Current Behavior**
If you use ^C (Ctrl + C) to prematurely cancel a command before you run it, the prompt somewhat derps out and overwrites the last line.

**Expected Behavior**
The prompt would not overwrite the last line and it would look perfect.

**Environment**
- Spacefish version: N/A; No output
- Fish version: `fish, version 2.7.1`
- Fish plugin manager: `oh-my-fish`
- Terminal emulator: `kitty`
- Operating system: `Solus (Linux 4.17.6, 64-bit)`

**Possible Solution**
Add an extra new line to make sure text doesn't get overwritten.

**Additional context/Screenshots**
[![asciicast](https://asciinema.org/a/cOAzs3d333n5wC9cFK4x4v1qI.png)](https://asciinema.org/a/cOAzs3d333n5wC9cFK4x4v1qI)

**Comment by matchai** [comment] 2018-07-25 04:47
Hey Snuggle!

Though I am unable to reproduce the issue on my config, it looks like this issue matches one that has been opened in `fish-shell`: https://github.com/fish-shell/fish-shell/issues/3537 

Hopefully this will be addressed in a future fish release. 😅

**Closed as completed** 2018-07-25 04:47 UTC

**Comment by Snuggle** [comment] 2018-07-25 04:49
Do you have a fix for this in your own fish config, since this is default behavior for 2.7.1, or do you use a single-line prompt?

**Comment by matchai** [comment] 2018-07-25 19:38
I'm not completely sure why this doesn't happen on my machine. I'm running 2.7.1 with a two-line prompt. I'm thinking it may be due to how iTerm handles repainting.

I have a pretty lightweight [fish.config](https://github.com/matchai/dotfiles/blob/master/.config/fish/config.fish), so I don't think I inadvertently fixed it. 🤔
