### ISSUE TITLE
Kubernetes included with Docker 18.09 sets the kubectl-section to always be enabled

### ISSUE THREAD

**Issue by MindTooth** [matchai/spacefish#111] opened 2018-11-23 15:39 UTC
## Bug Report

**Current Behavior**
With the recently released Docker 18.09 (Version 2.0.0.0-mac78), I experience that the Kubernetes section is always enabled.  The reason for that is Kubernetes is now included with Docker, and the `kubectl` command is therefore always present.  The current check is only wether if the command is present or not.

**Expected Behavior**
The prompt added with https://github.com/matchai/spacefish/pull/76 should only be visible when needed.  Inside a config folder (Dockerfile, etc.  Don't know how Kube works.)

**Environment**
- Spacefish version: [the output of `echo $SPACEFISH_VERSION`]
1.9
- Fish version: [the output of `fish --version`]
fish, version 2.7.1-1181-g18a163dc
- Fish plugin manager: [e.g. oh-my-fish, fisher, fin]
fundle
- Terminal emulator: [e.g. iTerm, Hyper, Terminator]
kitty
- Operating system: [e.g. OSX 10.13.4, Windows 10]
macOS Mojave

**Possible Solution**

Only load the section when needed.

**Additional context/Screenshots**

Add any other context about the problem here. If applicable, add screenshots to help explain.
<img width="236" alt="screenshot 2018-11-23 at 16 17 03" src="https://user-images.githubusercontent.com/33870508/48950384-3d93b780-ef3b-11e8-8208-8bc53998bc8e.png">

**Comment by matchai** [comment] 2018-11-25 05:42
It looks to me like this same issue would occur on [spaceship](https://github.com/denysdovhan/spaceship-prompt) with the latest version of Docker.
I think it would be best if we let them address it first.

++ @salmanulfarzy in case they want to open an issue

**Comment by matchai** [comment] 2018-11-30 20:43
Upon further investigation, it looks like this same issue doesn't occur on Spaceship ZSH 3.8.1 (latest right now). I'll see if I can find the cause of the problem. 🕵️

**Comment by matchai** [comment] 2018-11-30 20:52
Looks I missed a bit of logic when reading over the spaceship implementation. 😅
Should be quickly fixed with the upcoming PR.

Sorry for the wait!

**Closed as completed** 2018-12-03 16:38 UTC
Labels: Type: Bug, D1 - Difficulty: Trivial, P3 - Priority: High, Status: In Progress
